name: shopping_app
description: "Shopping Cart Project"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  shared_preferences: ^2.3.3
  http: ^1.4.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  animated_icon: ^0.0.9
  loading_animation_widget: ^1.3.0
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  random_string: ^2.3.1
  intl: ^0.20.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/
    - asset/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
