// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9D_eRzLLLvqU4Hc8AZ3_pJffgxmUWG8',
    appId: '1:634155670048:android:f10991c5744ef467037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIu0zKODfPc6Xi2kKrWG9wW1-0m4OhvNI',
    appId: '1:634155670048:ios:f46af2276a2fec81037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
    androidClientId: '634155670048-bt0jkb6elc883datq14dvlg2llma5tkd.apps.googleusercontent.com',
    iosClientId: '634155670048-5729qoud25b231cb9t2e5epcaoulu79i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatme',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMuzh2zoLhod1pSs7UIwLQENozbubTzQ',
    appId: '1:634155670048:web:5976bb8aec9a03fa037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    authDomain: 'my-flutter-app-2750c.firebaseapp.com',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
    measurementId: 'G-ZCFM7YL3L4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIu0zKODfPc6Xi2kKrWG9wW1-0m4OhvNI',
    appId: '1:634155670048:ios:f46af2276a2fec81037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
    androidClientId: '634155670048-bt0jkb6elc883datq14dvlg2llma5tkd.apps.googleusercontent.com',
    iosClientId: '634155670048-5729qoud25b231cb9t2e5epcaoulu79i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfMuzh2zoLhod1pSs7UIwLQENozbubTzQ',
    appId: '1:634155670048:web:b2bf079a293870cd037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    authDomain: 'my-flutter-app-2750c.firebaseapp.com',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
    measurementId: 'G-RWL6LMS3MY',
  );

}